const vehiclesData = [
    {
        id: 1,
        name: "Mercedes Benz C-Class",
        brand: "Mercedes",
        model: "Benz C-Class",
        type: "sedan",
        year: 2023,
        price: 700000,
        image: "images/car-1.jpg",
        transmission: "Automatic",
        fuel: "Petrol",
        seats: 4,
        available: true,
        features: ["Airconditions", "Child Seat", "GPS", "Luggage", "Music", "Seat Belt"],
        description: "A luxurious and comfortable sedan with the latest technology. Perfect for business trips or a special occasion."
    },
    {
        id: 2,
        name: "Tesla Model S",
        brand: "Tesla",
        model: "Model S",
        type: "sedan",
        year: 2024,
        price: 900000,
        image: "images/car-2.jpg",
        transmission: "Automatic",
        fuel: "Electric",
        seats: 5,
        available: true,
        features: ["Airconditions", "GPS", "Music", "Seat Belt", "Bluetooth", "Autopilot"],
        description: "Experience the future of driving with this sleek, powerful, and eco-friendly electric car."
    },
    {
        id: 3,
        name: "BMW M4",
        brand: "BMW",
        model: "M4",
        type: "sedan",
        year: 2023,
        price: 850000,
        image: "images/car-3.jpg",
        transmission: "Automatic",
        fuel: "Petrol",
        seats: 4,
        available: false,
        features: ["Airconditions", "GPS", "Music", "Seat Belt", "Sunroof"],
        description: "A high-performance sports car that delivers thrilling speed and precision handling."
    },
    {
        id: 4,
        name: "Ford Mustang",
        brand: "Ford",
        model: "Mustang",
        type: "sedan",
        year: 2022,
        price: 650000,
        image: "images/car-4.jpg",
        transmission: "Manual",
        fuel: "Petrol",
        seats: 4,
        available: true,
        features: ["Airconditions", "Music", "Seat Belt", "Powerful Engine"],
        description: "The iconic American muscle car, offering a raw and engaging driving experience."
    },
    {
        id: 5,
        name: "Toyota Camry",
        brand: "Toyota",
        model: "Camry",
        type: "sedan",
        year: 2023,
        price: 500000,
        image: "images/car-5.jpg",
        transmission: "Automatic",
        fuel: "Hybrid",
        seats: 5,
        available: true,
        features: ["Airconditions", "GPS", "Music", "Seat Belt", "Bluetooth", "Fuel Efficient"],
        description: "A reliable and fuel-efficient sedan, perfect for family trips and daily commuting."
    },
    {
        id: 6,
        name: "Honda CR-V",
        brand: "Honda",
        model: "CR-V",
        type: "suv",
        year: 2023,
        price: 600000,
        image: "images/car-6.jpg",
        transmission: "Automatic",
        fuel: "Petrol",
        seats: 5,
        available: true,
        features: ["Airconditions", "GPS", "Luggage", "Music", "Seat Belt", "Spacious"],
        description: "A versatile and spacious SUV with a comfortable ride and plenty of cargo space."
    },
    {
        id: 7,
        name: "Audi A4",
        brand: "Audi",
        model: "A4",
        type: "sedan",
        year: 2022,
        price: 720000,
        image: "images/car-7.jpg",
        transmission: "Automatic",
        fuel: "Petrol",
        seats: 5,
        available: false,
        features: ["Airconditions", "GPS", "Music", "Seat Belt", "Virtual Cockpit"],
        description: "A sophisticated and stylish sedan with a premium interior and advanced technology."
    },
    {
        id: 8,
        name: "Hyundai Ioniq 5",
        brand: "Hyundai",
        model: "Ioniq 5",
        type: "suv",
        year: 2023,
        price: 750000,
        image: "images/car-8.jpg",
        transmission: "Automatic",
        fuel: "Electric",
        seats: 5,
        available: true,
        features: ["Airconditions", "GPS", "Music", "Seat Belt", "Fast Charging"],
        description: "A futuristic-looking electric SUV with a spacious interior and impressive range."
    },
    {
        id: 9,
        name: "Mitsubishi Pajero Sport",
        brand: "Mitsubishi",
        model: "Pajero Sport",
        type: "suv",
        year: 2022,
        price: 680000,
        image: "images/car-9.jpg",
        transmission: "Automatic",
        fuel: "Diesel",
        seats: 7,
        available: true,
        features: ["Airconditions", "GPS", "Luggage", "Music", "Seat Belt", "Off-road capability"],
        description: "A rugged and capable SUV that can handle any terrain, perfect for adventurous families."
    },
    {
        id: 10,
        name: "Daihatsu Xenia",
        brand: "Daihatsu",
        model: "Xenia",
        type: "mpv",
        year: 2023,
        price: 350000,
        image: "images/car-10.jpg",
        transmission: "Manual",
        fuel: "Petrol",
        seats: 7,
        available: true,
        features: ["Airconditions", "Music", "Seat Belt", "Affordable"],
        description: "An affordable and practical MPV that is perfect for large families or group trips."
    },
    {
        id: 11,
        name: "Wuling Air EV",
        brand: "Wuling",
        model: "Air EV",
        type: "hatchback",
        year: 2023,
        price: 300000,
        image: "images/car-11.jpg",
        transmission: "Automatic",
        fuel: "Electric",
        seats: 4,
        available: true,
        features: ["Airconditions", "Music", "Seat Belt", "Compact", "Easy to park"],
        description: "A compact and agile electric car, ideal for navigating busy city streets."
    },
    {
        id: 12,
        name: "Jeep Wrangler",
        brand: "Jeep",
        model: "Wrangler",
        type: "suv",
        year: 2022,
        price: 800000,
        image: "images/car-12.jpg",
        transmission: "Automatic",
        fuel: "Petrol",
        seats: 4,
        available: false,
        features: ["Airconditions", "GPS", "Music", "Seat Belt", "Removable Roof"],
        description: "The ultimate off-road machine, offering unparalleled freedom and adventure."
    }
];

// Export ke window object agar bisa diakses dari file lain
window.vehicles = vehiclesData;

// Debug: pastikan data tersedia
console.log('data.js loaded successfully');
console.log('vehiclesData length:', vehiclesData.length);
console.log('window.vehicles length:', window.vehicles.length); 